# Generated by Django 4.1.2 on 2023-10-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='int_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('function_name', models.CharField(max_length=100)),
                ('function_function', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'int_info',
            },
        ),
    ]
