# Generated by Django 4.1.2 on 2023-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_info',
            name='function_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='int_info',
            name='function_input',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
