# Generated by Django 4.1.2 on 2024-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_address',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
