# Generated by Django 4.1.2 on 2024-01-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_users_password_users_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='points',
            field=models.IntegerField(),
        ),
    ]
