# Generated by Django 4.1.2 on 2024-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_users_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_info',
            name='function_tags',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
