# Generated by Django 4.1.2 on 2024-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_int_info_function_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
